CREATE TABLE Demo_Condition (
    ID INTEGER IDENTITY PRIMARY KEY,
    BundleId VARCHAR(128),
    BundleTimestamp TIMESTAMP,
    PatientId VARCHAR(128),
    PatientIdentifier VARCHAR(128),
    PatientName VARCHAR(200),
    PatientGender VARCHAR(32),
    PatientBirthDate DATE,
    ConditionId VARCHAR(128),
    ConditionIdentifier VARCHAR(128),
    ClinicalStatus VARCHAR(64),
    VerificationStatus VARCHAR(64),
    Category VARCHAR(64),
    ConditionCode VARCHAR(64),
    ConditionText VARCHAR(500),
    OnsetDateTime TIMESTAMP,
    AbatementDateTime TIMESTAMP,
    RecordedDate TIMESTAMP,
    Recorder VARCHAR(200),
    Asserter VARCHAR(200),
    InstitutionNumber VARCHAR(64),
    Department VARCHAR(200),
    DiagnosisType VARCHAR(100),
    RawConditionJson LONGVARCHAR,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
